#' @title Add haplotypes
#'
#' @description Add haplotypes at a locus of interest to CC data frame
#'
#' @param df
#' @param haplos Data frame, contains haplotype assignments for each CC strain as generated by haploscores.
#' @param locus.name Character, name assigned to the locus (e.g. "chr1").
#'
#' @return df
#'
#' @examples
#'
#' @export

addhap <- function(df,haplos,locus.name) {

  add.stat.base <- function(df,haplos,locus.name) {
    if(any("founders" %in% colnames(haplos))){
      haplos <- haplos[c(colnames(haplos[1]),"allele.effects","founders")]

      colnames(haplos)[1] <- "sire"
      df <- merge(df,haplos)
      names(df)[names(df) == 'allele.effects'] <- paste0("sire_",locus.name)
      names(df)[names(df) == 'founders'] <- paste0("sire.founder_",locus.name)

      colnames(haplos)[1] <- "dam"
      df <- merge(df,haplos)
      names(df)[names(df) == 'allele.effects'] <- paste0("dam_",locus.name)
      names(df)[names(df) == 'founders'] <- paste0("dam.founder_",locus.name)
    } else {
      haplos <- haplos[c(colnames(haplos[1]),"allele.effects")]

      colnames(haplos)[1] <- "sire"
      df <- merge(df,haplos)
      names(df)[names(df) == 'allele.effects'] <- paste0("sire_",locus.name)

      colnames(haplos)[1]="dam"
      df <- merge(df,haplos)
      names(df)[names(df) == 'allele.effects'] <- paste0("dam_",locus.name)
    }

    df$additive <- rowSums(df[c(paste0("dam_",locus.name),paste0("sire_",locus.name))])
    df$additive <- as.character(df$additive)
    df$additive <- as.factor(df$additive)
    names(df)[names(df) == 'additive'] <- paste0("add_",locus.name)

    labels <- apply(df[,c(paste0("dam_",locus.name),paste0("sire_",locus.name))], 1, sort)
    df$combo <- factor(apply(labels, 2, function(x) paste(x, collapse="_")))
    names(df)[names(df) == 'combo'] <- paste0("combo_",locus.name)

    return(df)
  }
  if(any("RIX" %in% colnames(df)) && any(!("dam" %in% colnames(df)))) {
    df <- rixsplit(df)
    df <- add.stat.base(df,haplos,locus.name)
  } else {
    if(any("dam" %in% colnames(df))){
      df <- add.stat.base(df,haplos,locus.name)
    } else {
      colnames(haplos)[1] <- colnames(df)[1]
      df <- merge(df,haplos)
      names(df)[names(df) == 'allele.effects'] <- locus.name
    }
  }
  return(df)
}


#' @title Add Mx1
#'
#' @description Add Mx1 allele status to a CC data frame
#'
#' @param df
#' @param haplos Data frame, contains haplotype assignments for each CC strain as generated by haploscores.
#' @param locus.name Character, name assigned to the locus (e.g. "chr1").
#' @param cast.score Numeric (0, 0.5, or 1).
#'
#' @return df
#'
#' @examples
#'
#' @export

addmx1  <-  function(df,haplos,locus.name,cast.score=0.5){
  if (cast.score==1) cast.col=9
  if (cast.score==0.5) cast.col=10
  if (cast.score==0) cast.col=11
  if (missing(cast.score)) cast.col=10

  mx1.score <- mx1[c(1,2,cast.col)]
  colnames(mx1.score)[3] <- "allele.effects"

  addhap(df,haplos=mx1.score,locus.name="mx1")
  return(df)
}
